# Generated by Django 5.2 on 2025-04-13 17:45

import django.core.validators
import django.db.models.deletion
import imagekit.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('institution', models.CharField(max_length=100)),
                ('certificate_id', models.CharField(blank=True, max_length=50)),
                ('certificate_url', models.URLField(blank=True)),
                ('completion_date', models.DateField()),
                ('duration_hours', models.PositiveIntegerField(blank=True, null=True)),
                ('instructor', models.CharField(blank=True, max_length=100)),
                ('accreditation', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'ordering': ['-completion_date'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('description', models.TextField()),
                ('detailed_description', models.TextField(blank=True)),
                ('image', models.ImageField(upload_to='projects/')),
                ('thumbnail', imagekit.models.fields.ProcessedImageField(blank=True, upload_to='projects/thumbnails')),
                ('github_url', models.URLField(blank=True)),
                ('live_url', models.URLField(blank=True)),
                ('featured', models.BooleanField(default=False)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('client', models.CharField(blank=True, max_length=100)),
                ('project_type', models.CharField(choices=[('personal', 'Personal Project'), ('client', 'Client Work'), ('open-source', 'Open Source')], max_length=20)),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('proficiency', models.PositiveIntegerField(default=70, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('category', models.CharField(choices=[('backend', 'Backend'), ('frontend', 'Frontend'), ('devops', 'DevOps'), ('design', 'Design'), ('language', 'Language')], max_length=20)),
                ('icon', models.CharField(blank=True, help_text='Font Awesome icon class (e.g. fa-python)', max_length=30)),
                ('years_experience', models.DecimalField(decimal_places=1, default=1.0, max_digits=3)),
                ('showcase', models.BooleanField(default=True, help_text='Display on skills section')),
            ],
            options={
                'ordering': ['-proficiency', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ProjectSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('importance', models.PositiveIntegerField(choices=[(1, 'Basic'), (3, 'Medium'), (5, 'Core')], default=5)),
                ('usage_description', models.CharField(blank=True, max_length=200)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='protfolio.project')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='protfolio.skill')),
            ],
            options={
                'unique_together': {('project', 'skill')},
            },
        ),
        migrations.AddField(
            model_name='project',
            name='skills_used',
            field=models.ManyToManyField(through='protfolio.ProjectSkill', to='protfolio.skill'),
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree', models.CharField(max_length=100)),
                ('institution', models.CharField(max_length=100)),
                ('field_of_study', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('currently_attending', models.BooleanField(default=False)),
                ('logo', models.ImageField(blank=True, upload_to='education/logos/')),
                ('skills_gained', models.ManyToManyField(to='protfolio.skill')),
            ],
            options={
                'verbose_name_plural': 'Education',
            },
        ),
        migrations.CreateModel(
            name='CourseSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mastery_level', models.CharField(choices=[('introduced', 'Introduced'), ('practiced', 'Practiced'), ('mastered', 'Mastered')], max_length=20)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='protfolio.course')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='protfolio.skill')),
            ],
            options={
                'unique_together': {('course', 'skill')},
            },
        ),
        migrations.AddField(
            model_name='course',
            name='skills_covered',
            field=models.ManyToManyField(through='protfolio.CourseSkill', to='protfolio.skill'),
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=100)),
                ('company', models.CharField(blank=True, max_length=100)),
                ('content', models.TextField()),
                ('avatar', models.ImageField(blank=True, upload_to='testimonials/')),
                ('featured', models.BooleanField(default=False)),
                ('date_received', models.DateField()),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='testimonials', to='protfolio.project')),
            ],
            options={
                'ordering': ['-date_received'],
            },
        ),
    ]
