# Generated by Django 5.2 on 2025-04-19 09:06

import imagekit.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protfolio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
                ('phone', models.CharField(blank=True, max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='project',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(blank=True, upload_to='protfolio/static/protfolio/images/projects'),
        ),
        migrations.AlterField(
            model_name='project',
            name='thumbnail',
            field=imagekit.models.fields.ProcessedImageField(blank=True, upload_to='protfolio/static/protfolio/images/projects/thumbnails'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='category',
            field=models.CharField(choices=[('webdev', 'WebDev'), ('ai', 'AI'), ('devops', 'DevOps'), ('design', 'Design'), ('language', 'Language'), ('all', 'All')], max_length=20),
        ),
        migrations.AlterField(
            model_name='skill',
            name='icon',
            field=models.CharField(blank=True, help_text='Font Awesome icon class (e.g. fa-python)', max_length=50),
        ),
    ]
