# Generated by Django 5.2 on 2025-04-24 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('protfolio', '0004_project_description_fa_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='slug_fa',
        ),
        migrations.RemoveField(
            model_name='project',
            name='title_fa',
        ),
    ]
