# Generated by Django 5.2 on 2025-04-24 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protfolio', '0005_remove_project_slug_fa_remove_project_title_fa'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='title_fa',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
