# Generated by Django 5.2 on 2025-04-20 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protfolio', '0002_contactmessage_alter_project_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='user_ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='message',
            field=models.TextField(max_length=1000),
        ),
    ]
