# Generated by Django 5.2 on 2025-04-24 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protfolio', '0003_contactmessage_user_ip_alter_contactmessage_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='description_fa',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='detailed_description_fa',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='slug_fa',
            field=models.SlugField(max_length=200, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='project',
            name='title_fa',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_type',
            field=models.CharField(choices=[('personal', 'Personal Project'), ('client', 'Client Work'), ('open-source', 'Open Source')], default='personal', max_length=20),
        ),
    ]
